description = "Simple hello world tool that greets a person"
keywords = ["hello", "greet", "test"]

[[parameters]]
name = "name"
type = "string"
description = "Name of the person to greet"
required = true

[[parameters]]
name = "times"
type = "int"
description = "Number of times to repeat the greeting"
required = false
